/* Generated by tools/media/generate-difficulty-strips.mjs. */
import type { ImageSourcePropType } from 'react-native';

type DifficultyStrip = { rating: number; source: ImageSourcePropType };

const PACK_DIFFICULTY_STRIPS: Record<string, DifficultyStrip> = {
  club_akron: {
    rating: 4,
    source: require('../clubs/carousel/difficulty/club_akron_4.webp'),
  },
  club_akhmat: {
    rating: 4,
    source: require('../clubs/carousel/difficulty/club_akhmat_4.webp'),
  },
  club_baltika: {
    rating: 3,
    source: require('../clubs/carousel/difficulty/club_baltika_3.webp'),
  },
  club_dinmah: {
    rating: 5,
    source: require('../clubs/carousel/difficulty/club_dinmah_5.webp'),
  },
  club_dinmos: {
    rating: 2,
    source: require('../clubs/carousel/difficulty/club_dinmos_2.webp'),
  },
  club_zenit: {
    rating: 1,
    source: require('../clubs/carousel/difficulty/club_zenit_1.webp'),
  },
  club_krasnodar: {
    rating: 2,
    source: require('../clubs/carousel/difficulty/club_krasnodar_2.webp'),
  },
  club_ks: {
    rating: 4,
    source: require('../clubs/carousel/difficulty/club_ks_4.webp'),
  },
  club_loko: {
    rating: 2,
    source: require('../clubs/carousel/difficulty/club_loko_2.webp'),
  },
  club_orenburg: {
    rating: 5,
    source: require('../clubs/carousel/difficulty/club_orenburg_5.webp'),
  },
  club_rodina: {
    rating: 5,
    source: require('../clubs/carousel/difficulty/club_rodina_5.webp'),
  },
  club_rostov: {
    rating: 3,
    source: require('../clubs/carousel/difficulty/club_rostov_3.webp'),
  },
  club_rubin: {
    rating: 3,
    source: require('../clubs/carousel/difficulty/club_rubin_3.webp'),
  },
  club_spartak: {
    rating: 1,
    source: require('../clubs/carousel/difficulty/club_spartak_1.webp'),
  },
  club_fakel: {
    rating: 5,
    source: require('../clubs/carousel/difficulty/club_fakel_5.webp'),
  },
  club_cska: {
    rating: 1,
    source: require('../clubs/carousel/difficulty/club_cska_1.webp'),
  },
  stadium_pfl: {
    rating: 5,
    source: require('../clubs/carousel/difficulty/stadium_pfl_5.webp'),
  },
  stadium_fnl: {
    rating: 4,
    source: require('../clubs/carousel/difficulty/stadium_fnl_4.webp'),
  },
  stadium_rpl: {
    rating: 3,
    source: require('../clubs/carousel/difficulty/stadium_rpl_3.webp'),
  },
  logo_fnl2: {
    rating: 4,
    source: require('../clubs/carousel/difficulty/logo_fnl2_4.webp'),
  },
  logo_twolig: {
    rating: 4,
    source: require('../clubs/carousel/difficulty/logo_twolig_4.webp'),
  },
  logo_media: {
    rating: 4,
    source: require('../clubs/carousel/difficulty/logo_media_4.webp'),
  },
  logo_fnl: {
    rating: 3,
    source: require('../clubs/carousel/difficulty/logo_fnl_3.webp'),
  },
  logo_rpl: {
    rating: 1,
    source: require('../clubs/carousel/difficulty/logo_rpl_1.webp'),
  },
  logo_hidden: {
    rating: 5,
    source: require('../clubs/carousel/difficulty/logo_hidden_5.webp'),
  },
};

export function getClubDifficultyStripSource(
  packId: string,
): ImageSourcePropType | null {
  return PACK_DIFFICULTY_STRIPS[packId]?.source ?? null;
}
