/* Generated by scripts/generate-cup-theme-assets.mjs. */
import type { ImageSourcePropType } from 'react-native';
import type { CupTeamLogoPaletteId } from '../../../lib/cup/cupTeamLogo';

export interface CupThemeAssets {
  background: ImageSourcePropType;
  setupIntro: ImageSourcePropType;
  setupForm: ImageSourcePropType;
  logoPreview: ImageSourcePropType;
  matchHeader: ImageSourcePropType;
  stageFrame: ImageSourcePropType;
  stageFirstFrame: ImageSourcePropType;
  vs: ImageSourcePropType;
  arrowLeft: ImageSourcePropType;
  arrowRight: ImageSourcePropType;
  commentIgor: ImageSourcePropType;
  commentDmitri: ImageSourcePropType;
  tournament: ImageSourcePropType;
  achievement: ImageSourcePropType;
  nextButton: ImageSourcePropType;
  regameButton: ImageSourcePropType;
  title_cup_128: ImageSourcePropType;
  title_cup_64: ImageSourcePropType;
  title_cup_32: ImageSourcePropType;
  title_cup_16: ImageSourcePropType;
  title_cup_8: ImageSourcePropType;
  title_cup_4: ImageSourcePropType;
  title_cup_2: ImageSourcePropType;
  title_cup_2_down: ImageSourcePropType;
  title_cup_f: ImageSourcePropType;
  title_cup_s: ImageSourcePropType;
  backgroundCreate: ImageSourcePropType;
  backgroundStage: ImageSourcePropType;
  backgroundLose: ImageSourcePropType;
  backgroundWait: ImageSourcePropType;
  backgroundWinTrophy: ImageSourcePropType;
  backFans: ImageSourcePropType;
  backProcent: ImageSourcePropType;
  backComment: ImageSourcePropType;
  fun1: ImageSourcePropType;
  fun2: ImageSourcePropType;
  fun3: ImageSourcePropType;
  fun4: ImageSourcePropType;
  fun5: ImageSourcePropType;
  fun6: ImageSourcePropType;
}

const GOLD_CUP_THEME_ASSETS: CupThemeAssets = {
  background: require('./themes/gold/background.webp'),
  setupIntro: require('./themes/gold/setupIntro.webp'),
  setupForm: require('./themes/gold/setupForm.webp'),
  logoPreview: require('./themes/gold/logoPreview.webp'),
  matchHeader: require('./themes/gold/matchHeader.webp'),
  stageFrame: require('./themes/gold/stageFrame.webp'),
  stageFirstFrame: require('./themes/gold/stageFirstFrame.webp'),
  vs: require('./themes/gold/vs.webp'),
  arrowLeft: require('./themes/gold/arrowLeft.webp'),
  arrowRight: require('./themes/gold/arrowRight.webp'),
  commentIgor: require('./themes/gold/commentIgor.webp'),
  commentDmitri: require('./themes/gold/commentDmitri.webp'),
  tournament: require('./themes/gold/tournament.webp'),
  achievement: require('./themes/gold/achievement.webp'),
  nextButton: require('./themes/gold/nextButton.webp'),
  regameButton: require('./themes/gold/regameButton.webp'),
  title_cup_128: require('./themes/gold/title_cup_128.webp'),
  title_cup_64: require('./themes/gold/title_cup_64.webp'),
  title_cup_32: require('./themes/gold/title_cup_32.webp'),
  title_cup_16: require('./themes/gold/title_cup_16.webp'),
  title_cup_8: require('./themes/gold/title_cup_8.webp'),
  title_cup_4: require('./themes/gold/title_cup_4.webp'),
  title_cup_2: require('./themes/gold/title_cup_2.webp'),
  title_cup_2_down: require('./themes/gold/title_cup_2_down.webp'),
  title_cup_f: require('./themes/gold/title_cup_f.webp'),
  title_cup_s: require('./themes/gold/title_cup_s.webp'),
  backgroundCreate: require('./themes/gold/background_create.webp'),
  backgroundStage: require('./themes/gold/background_stage.webp'),
  backgroundLose: require('./themes/gold/background_lose.webp'),
  backgroundWait: require('./themes/gold/background_wait.webp'),
  backgroundWinTrophy: require('./themes/gold/background_win_trophy.webp'),
  backFans: require('./themes/gold/back_fans.webp'),
  backProcent: require('./themes/gold/back_procent.webp'),
  backComment: require('./themes/gold/back_comment.webp'),
  fun1: require('./themes/gold/fun_1.webp'),
  fun2: require('./themes/gold/fun_2.webp'),
  fun3: require('./themes/gold/fun_3.webp'),
  fun4: require('./themes/gold/fun_4.webp'),
  fun5: require('./themes/gold/fun_5.webp'),
  fun6: require('./themes/gold/fun_6.webp'),
};

export function getCupThemeAssets(_paletteId: CupTeamLogoPaletteId): CupThemeAssets {
  return GOLD_CUP_THEME_ASSETS;
}
