/* Generated by scripts/generate-cup-theme-assets.mjs. */
import type { ImageSourcePropType } from 'react-native';
import type { CupTeamLogoPaletteId } from '../../../lib/cup/cupTeamLogo';

export interface CupThemeAssets {
  background: ImageSourcePropType;
  setupIntro: ImageSourcePropType;
  matchHeader: ImageSourcePropType;
  arrowLeft: ImageSourcePropType;
  arrowRight: ImageSourcePropType;
  commentIgor: ImageSourcePropType;
  commentDmitri: ImageSourcePropType;
  tournament: ImageSourcePropType;
  achievement: ImageSourcePropType;
  nextButton: ImageSourcePropType;
  backgroundCreate: ImageSourcePropType;
  fun1: ImageSourcePropType;
  fun2: ImageSourcePropType;
  fun3: ImageSourcePropType;
  fun4: ImageSourcePropType;
  fun5: ImageSourcePropType;
  fun6: ImageSourcePropType;
}

const GOLD_CUP_THEME_ASSETS: CupThemeAssets = {
  background: require('./themes/gold/background.webp'),
  setupIntro: require('./themes/gold/setupIntro.webp'),
  matchHeader: require('./themes/gold/matchHeader.webp'),
  arrowLeft: require('./themes/gold/arrowLeft.webp'),
  arrowRight: require('./themes/gold/arrowRight.webp'),
  commentIgor: require('./themes/gold/commentIgor.webp'),
  commentDmitri: require('./themes/gold/commentDmitri.webp'),
  tournament: require('./themes/gold/tournament.webp'),
  achievement: require('./themes/gold/achievement.webp'),
  nextButton: require('./themes/gold/nextButton.webp'),
  backgroundCreate: require('./themes/gold/background_create.webp'),
  fun1: require('./themes/gold/fun_1.webp'),
  fun2: require('./themes/gold/fun_2.webp'),
  fun3: require('./themes/gold/fun_3.webp'),
  fun4: require('./themes/gold/fun_4.webp'),
  fun5: require('./themes/gold/fun_5.webp'),
  fun6: require('./themes/gold/fun_6.webp'),
};

export function getCupThemeAssets(_paletteId: CupTeamLogoPaletteId): CupThemeAssets {
  return GOLD_CUP_THEME_ASSETS;
}
