/* Generated by scripts/generate-cup-theme-assets.mjs. */
import type { ImageSourcePropType } from 'react-native';
import type { CupTeamLogoPaletteId } from '../../../lib/cup/cupTeamLogo';

export interface CupThemeAssets {
  background: ImageSourcePropType;
  setupIntro: ImageSourcePropType;
  matchHeader: ImageSourcePropType;
  arrowLeft: ImageSourcePropType;
  arrowRight: ImageSourcePropType;
  commentIgor: ImageSourcePropType;
  commentDmitri: ImageSourcePropType;
  tournament: ImageSourcePropType;
  achievement: ImageSourcePropType;
  nextButton: ImageSourcePropType;
  backgroundCreate: ImageSourcePropType;
}

const GOLD_CUP_THEME_ASSETS: CupThemeAssets = {
  background: require('./themes/gold/background.webp'),
  setupIntro: require('./themes/gold/setupIntro.webp'),
  matchHeader: require('./themes/gold/matchHeader.webp'),
  arrowLeft: require('./themes/gold/arrowLeft.webp'),
  arrowRight: require('./themes/gold/arrowRight.webp'),
  commentIgor: require('./themes/gold/commentIgor.webp'),
  commentDmitri: require('./themes/gold/commentDmitri.webp'),
  tournament: require('./themes/gold/tournament.webp'),
  achievement: require('./themes/gold/achievement.webp'),
  nextButton: require('./themes/gold/nextButton.webp'),
  backgroundCreate: require('./themes/gold/background_create.webp'),
};

export function getCupThemeAssets(_paletteId: CupTeamLogoPaletteId): CupThemeAssets {
  return GOLD_CUP_THEME_ASSETS;
}
